'use strict';

const path = require('path');
const { spawnSync } = require('child_process');

const tests = [
  'static-site.test.js',
  'athena-write-contract.test.js',
  'athena-action-contract.test.js',
  'athena-confirmation-runtime.test.js',
  'athena-unified-manifest-contract.test.js',
  'orders-unified-review-contract.test.js',
  'orders-human-place-button.test.js',
  'athena-order-action-runtime.test.js',
  'athena-unified-confirmation-contract.test.js',
  'athena-unified-confirmation-runtime.test.js',
  'destination-teaching-runtime.test.js',
  'athena-advanced-unified-entry-contract.test.js',
  'athena-session-preservation-contract.test.js',
  'athena-session-health-runtime.test.js',
  'athena-confirmed-billing-contract.test.js',
  'athena-adversarial-contract.test.js',
  'primary-workflow-contract.test.js',
  'boot-loading-visual-contract.test.js',
  'boot-loading-lifecycle-runtime.test.js',
  'progress-stages-runtime.test.js',
  'interaction-performance-contract.test.js',
  'scribeflow-inline-syntax.test.js',
  'startup-hydration-contract.test.js',
  'day-progress-time-runtime.test.js',
  'day-progress-responsive-layout-contract.test.js',
  'easy-transcript-continuity.test.js',
  'easy-lane-engine-rewrite-runtime.test.js',
  'easy-pause-resume-runtime.test.js',
  'async-artifact-binding-contract.test.js',
  'async-artifact-source-guard.test.js',
  'note-editor-binding-contract.test.js',
  'dictate-anywhere-binding-contract.test.js',
  'record-backup-lifecycle.test.js',
  'autosave-patient-scope-runtime.test.js',
  'voice-ai-binding-contract.test.js',
  'assistant-readiness-runtime.test.js',
  'assistant-production-runtime.test.js',
  'copilot-request-binding-contract.test.js',
  'async-owner-guards.test.js',
  'history-duplicate-name-binding.test.js',
  'manual-history-exact-open-mrn-contract.test.js',
  'history-preopened-same-tab-contract.test.js',
  'history-absolute-deadline-runtime.test.js',
  'background-final-patient-timeout-runtime.test.js',
  'appointment-id-bootstrap-contract.test.js',
  'day-schedule-absolute-deadline-runtime.test.js',
  'schedule-scrape-deadline-searchopen-runtime.test.js',
  'background-all-visits-cleanup-serialization.test.js',
  'quiet-pull-pending-release-runtime.test.js',
  'chart-request-deadline-runtime.test.js',
  'patient-chart-parse-abort-runtime.test.js',
  'chart-refresh-merge-runtime.test.js',
  'provider-day-history-cards-runtime.test.js',
  'full-visit-reader-runtime.test.js',
  'visit-reader-minimal-deadline-contract.test.js',
  'visit-request-correlation-runtime.test.js',
  'cohort-request-correlation-runtime.test.js',
  'visit-accordion-body-runtime.test.js',
  'history-organization-runtime.test.js',
  'history-organization-adversarial.test.js',
  'history-ingestion-card-hardening.test.js',
  'save-verify-managed-batch-toast.test.js',
  'athena-pull-toast-lifecycle.test.js',
  'athena-pull-notification-ownership.test.js',
  'opnote-exact-patient-binding.test.js',
  'opnote-staging-identity-runtime.test.js',
  'opnote-verified-history-repair-runtime.test.js',
  'template-library-runtime.test.js',
  'staging-history-writeflow-parity.test.js',
  'active-patient-sync-status.test.js',
  'voice-dock-layout-contract.test.js',
  'portal-invite-placement-runtime.test.js',
  'patient-card-contrast-contract.test.js',
  'patient-store-compression-runtime.test.js',
  'visit-shell-merge-alias-survival.test.js',
  'visit-pull-toggle-contract.test.js',
  'visit-wire-identity-guard-runtime.test.js',
  'unified-write-surface-contract.test.js',
  'schedule-time-contract.test.js',
  'schedule-pull-integrity.test.js',
  'schedule-packaged-reader-regression.test.js',
  'extension-schedule-support-diagnostic.test.js',
  'schedule-history-pipeline.test.js',
  'schedule-identity-adversarial-runtime.test.js',
  'schedule-row-demographics-adversarial.test.js',
  'schedule-visit-persistence-adversarial.test.js',
  'schedule-authoritative-empty-contract.test.js',
  'schedule-authoritative-reconciliation-runtime.test.js',
  'schedule-import-scan-performance-contract.test.js',
  'provider-day-pull-contract.test.js',
  'provider-month-exact-routing.test.js',
  'provider-roster-integrity.test.js',
  'provider-roster-machine-echo-collapse.test.js',
  'writeflow-athena-appointment-id-resolution.test.js',
  'provider-roster-provenance.test.js',
  'athena-tab-lease-over-pin.test.js',
  'status-notifier-guard.test.js',
  'schedule-nonpatient-row-guard.test.js',
  'provider-selector-sanitizer-runtime.test.js',
  'schedule-pull-ui-contract.test.js',
  'manual-history-retry-ui-runtime.test.js',
  'startup-explicit-pull-contract.test.js',
  'performance-lifecycle-contract.test.js',
  'extension-read-path.test.js',
  'extension-package.test.js',
  'extension-reload-helper-contract.test.js',
  'portal-staff-booking-contract.test.js',
  'settings-cleanup-contract.test.js',
  'study-natural-request-report.test.js',
  'study-academic-paper.test.js',
  'comp-report-contract.test.js',
  'prep-summary-debris.test.js',
  'visit-single-transcript-contract.test.js',
  'onboarding-tour-v2-contract.test.js',
  'device-role-contract.test.js',
  'extension-health-contract.test.js',
  'conn-status-truth-contract.test.js',
  'athena-window-guard-contract.test.js',
  'pull-request-correlation-contract.test.js',
  'shared-progress-runtime.test.js',
  'opnote-clinical-consistency-runtime.test.js',
  'opnote-generation-jobs-runtime.test.js'
];

for (const test of tests) {
  const file = path.join(__dirname, test);
  const r = spawnSync(process.execPath, [file], { stdio: 'inherit' });
  if (r.status !== 0) process.exit(r.status || 1);
}

console.log(`PASS all ${tests.length} local regression suites`);
